server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.174.130:3306/guli_cart?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456Abc@
  task:
    execution:
      thread-name-prefix: cart-task-
      pool:
        core-size: 100
        max-size: 500
        keep-alive: 60S
        queue-capacity: 5000
        allow-core-thread-timeout: true
      shutdown:
        await-termination: true
        await-termination-period: 60s
  rabbitmq:
    host: 192.168.174.130
    virtual-host: /lihan
    username: lihan
    password: lihan
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual
        concurrency: 3
  redis:
    host: 192.168.174.130
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
feign:
  sentinel:
    enabled: true
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
jwt:
  pubKeyPath:  D:\project\rsa\rsa.pub
  cookieName:  GMALL-TOKEN
  userKey:  user-key
  expire:  15552000
